gameboy : 
	gcc -O3 ../src/gameboy.c ../src/z80gb.c -o ../bin/gameboy -l SDL2 -l SDL2_ttf
debug : 
	gcc -gdwarf-4 -g3 -D "DEBUG" ../src/gameboy.c ../src/z80gb.c -o ../bin/gameboy -l SDL2 -l SDL2_ttf

